### ISSUE TITLE
A more accessible download link 

### ISSUE THREAD

**Issue by zanilzanzan** [vision4robotics/TCTrack#1]
Dear Ziang, first of all thanks for releasing the code for this promising pproach and making it publicly available. Is it possible to upload the pretrained model file to a more accessible platform, such as google drive or dropbox? That would be great, as it is not that straigthforward to download files from Baidu outside China, as far as I know. At least, my attempts were not successful so far. Thanks in advance!

**Comment by ziangcao0312** [comment]
Thanks for your attention. We have added the link to google drive
