### ISSUE TITLE
Can you provide result files for other comparison algorithms?

### ISSUE THREAD

**Issue by HonglinChu** [vision4robotics/TCTrack#11]
Thank you for your open source work in the field of UAV Tracking. We want to generate the results of  figure 6 in your paper, and can you provide the result files for other comparison algorithms? Very Grateful!

**Comment by triumph693** [comment]
> Thank you for your open source work in the field of UAV Tracking. We want to generate the results of figure 6 in your paper, and can you provide the result files for other comparison algorithms? Very Grateful!

Hello, have you found the tracking results of other algorithms? Could you share them? I would be very grateful .
