### ISSUE TITLE
评估结果咨询

### ISSUE THREAD

**Issue by triumph693** [vision4robotics/TCTrack#12]
您好，看了你们的论文，从里面受益很多，我看到SiamAPN++、SiamAPN、SiamAPN也是你们团队的论文，可以分享一下在DTB70和UAV123数据集上其他算法的跟踪结果么，我将非常感谢

**Comment by vision4robotics** [comment]
跟踪结果的prec和succ在文中已经指明，由于设备不同可能结果有所差异，最好还是控制变量统一在自己设备上评估。以下结果可用作参考（可直接用于使用OTB Toolkit matlab工具绘图
[results_OPE_UAV123.zip](https://github.com/vision4robotics/TCTrack/files/9073058/results_OPE_UAV123.zip)
[results_OPE_DTB.zip](https://github.com/vision4robotics/TCTrack/files/9073069/results_OPE_DTB.zip)
）

**Comment by triumph693** [comment]
非常感谢您，可不可以把其他之前的一些算法（您在图里画过的）在这两个数据集上的评估结果也给我发一下呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月8日(星期五) 晚上11:10
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vision4robotics/TCTrack] 评估结果咨询 (Issue #12)





 
跟踪结果的prec和succ在文中已经指明，由于设备不同可能结果有所差异，最好还是控制变量统一在自己设备上评估。以下结果可用作参考（可直接用于使用OTB Toolkit matlab工具绘图
 results_OPE_UAV123.zip
 results_OPE_DTB.zip
 ）
