### ISSUE TITLE
Thanks for the great work! Are TCTrack's results on the UAV112 benchmark incomplete?

### ISSUE THREAD

**Issue by Richard-lX** [vision4robotics/TCTrack#13]

**Comment by Richard-lX** [comment]
The provided UAV112_l results on TCTrack contain 45 files. It maybe incomplete!

**Comment by vision4robotics** [comment]
Thanks for your attention. Please note that TCTrack is evaluated on the UAVTrack112_l rather than UAVTrack112. The relationship between the two benchmarks is like the UAV123 and UAV123_L.
