### ISSUE TITLE
Can you provide a pre-trained configuration file on Imagenet?

### ISSUE THREAD

**Issue by marico2020** [vision4robotics/TCTrack#15]
Thank you for your open source work in the field of UAV Tracking! Can you provide a pre-trained configuration file on Imagenet?

**Comment by vision4robotics** [comment]
Thanks for your attention. We adopt the pre-trained model on Imagenet following SiamRPN++ (https://drive.google.com/drive/folders/1DuXVWVYIeynAcvt9uxtkuleV6bs6e3T9)
