### ISSUE TITLE
difference between TCT and TCTtest

### ISSUE THREAD

**Issue by 1145284121** [vision4robotics/TCTrack#2]
thanks for you great work

I am confused why different codes were used in the training and prediction phases (AT-Trans)
![image](https://user-images.githubusercontent.com/41956449/157887992-1c9e7282-0329-4190-a00b-fa53b26ea248.png)

**Comment by ziangcao0312** [comment]
Because when we train our tracker, we use the video. However, the input of the testing process is only one frame. So, to better illustrate our code, we split the test and train into two files.
