### ISSUE TITLE
Time series feature extraction

### ISSUE THREAD

**Issue by yingqiluoCSDN** [vision4robotics/TCTrack#21]
Hello, may I ask which module is extracting timing features and where in the code?

**Comment by ziangcao0312** [comment]
There are two modules which have related to temporal features. They are in pysot/models/backbone/[temporalbackbone.py](https://github.com/vision4robotics/TCTrack/blob/main/pysot/models/backbone/temporalbackbone.py) and [utile.py](https://github.com/vision4robotics/TCTrack/blob/main/pysot/models/utile_tctrack/utile.py)
