### ISSUE TITLE
About test_dataset

### ISSUE THREAD

**Issue by HULEIYI** [vision4robotics/TCTrack#22]
Could you provide the code for the preprocessing of the UAV123 dataset and other test dataset? I can't find the .json file in the raw UAV123 dataset, so maybe you have preprocessed it.

**Comment by ziangcao0312** [comment]
Thanks for your attention. You can find the json file in https://drive.google.com/drive/folders/10cfXjwQQBQeu48XMf2xc_W1LucpistPI

**Comment by Old-detective** [comment]
> Thanks for your attention. You can find the json file in https://drive.google.com/drive/folders/10cfXjwQQBQeu48XMf2xc_W1LucpistPI

Could you provide the code for the preprocessing of the UAVDT dataset and other test dataset? I can't find the .json file in the raw UAVDT dataset, so maybe you have preprocessed it.
