### ISSUE TITLE
ModuleNotFoundError: No module named 'pysot'

### ISSUE THREAD

**Issue by Rogersiy** [vision4robotics/TCTrack#32]
When I want to test TCTrack, I encountered this error. 
I test this on Ubuntu pytorch 1.6 CUDA 10.2

> Traceback (most recent call last):
>   File "./tools/test.py", line 14, in <module>
>     from pysot.core.config import cfg
> ModuleNotFoundError: No module named 'pysot'

**Comment by PROGAMMER-YANG** [comment]
Has this problem been solved？
