### ISSUE TITLE
UAVDT.json

### ISSUE THREAD

**Issue by Old-detective** [vision4robotics/TCTrack#36]
Who have the .json file in the UAVDT dataset ?  I have only .txt file in the UAVDT dataset !

**Comment by ziangcao0312** [comment]
We use the python files to process the txt data for generating json data. You can change some codes based on the uavtrack112.py (https://github.com/vision4robotics/TCTrack/blob/main/toolkit/datasets/uavtrack112.py) to evaluate the trackers on UAVDT

**Comment by Old-detective** [comment]
> We use the python files to process the txt data for generating json data. You can change some codes based on the uavtrack112.py (https://github.com/vision4robotics/TCTrack/blob/main/toolkit/datasets/uavtrack112.py) to evaluate the trackers on UAVDT

Thank you !
