### ISSUE TITLE
关于训练集

### ISSUE THREAD

**Issue by Old-detective** [vision4robotics/TCTrack#38]
在下载VID的时候，代码中提供的“wget http://bvisionweb1.cs.unc.edu/ilsvrc2015/ILSVRC2015_VID.tar.gz”访问不了，哪位大佬可以提供一下VID，got10k，lasot的数据集吗

**Comment by caijiyjn** [comment]
数据集合集（百度网盘）： 

链接：https://pan.baidu.com/s/1jl9FsrZh4xEqP6Ffh_t6FA 
提取码：3zlv
