### ISSUE TITLE
Questions about training dataset and real-world test

### ISSUE THREAD

**Issue by YUAN-xiaoying** [vision4robotics/TCTrack#40]
1. What does 'DATASET.VIDEOS_PER_EPOCH = 600000' in config.py mean? the number of videos or the number picture pairs?If the dataset is small, can I reduce this param to reduce the time of training?

**Comment by YUAN-xiaoying** [comment]
2. What is the setting of Nvidia AGX? The version of python supported by AGX is 3.6 when choose Py torch 1.6, but your code is based on python 3.8. How to deal with this issue?

**Comment by ziangcao0312** [comment]
1. The DATASET.VIDEOS_PER_EPOCH means how many iterations will be used in one epoch. If the dataset is small, you can reduce this param to reduce the time of training.
2. If you use the new version of jetpack>4.1, our code can be used on AGX directly. Pysot is support pytorch1.6.
