### ISSUE TITLE
如何测试visdrone2018结果？

### ISSUE THREAD

**Issue by Jasper0068** [vision4robotics/TCTrack#47]
已解决

**Comment by ChenConnie** [comment]
请问您是怎么解决的？

**Comment by Jasper0068** [comment]
> 请问您是怎么解决的？

请下载‘VisDrone2019-SOT-test-dev’文件夹，这里面包含完整的注释，不要下载‘VisDrone2019-SOT-test-challenge’文件，他只有第一帧，这是曾经用于visdrone2019挑战赛的
