### ISSUE TITLE
其他算法的results分享

### ISSUE THREAD

**Issue by Coder-TieHH** [vision4robotics/TCTrack#49]
您好，关注你们很多的工作了，从siamapn开始到++再到TCTrack，请问下方便分享下，您在论文中展示的其他的算法的结果嘛，就是除了SiamAPN++等你们开源的能找到，很多你们论文中提到的都找不到，我也是做无人机跟踪这块的最近写论文，苦于UAV数据集的对比太少，你的论文中非常详细，如果可以的话，非常感谢。

**Comment by ziangcao0312** [comment]
感谢您的关注，你可以从这两篇综述中找到我们的结果siamesetracking4uav（siamese） 和 DCFTracking4UAV. 也可以看https://github.com/zerolfl/V4R-evaluation。如果我们的工作可以帮助到您，请在您的工作中引用我们的工作

**Comment by Coder-TieHH** [comment]
好的，非常感谢你们的工作！
