### ISSUE TITLE
有关UAV123数据集读取的问题

### ISSUE THREAD

**Issue by dandervis** [vision4robotics/TCTrack#5]
您好，我想请教一下我按照您论文里的描述将UAV123数据集下载至tools目录下后运行test.py仍报错找不到json文件，请问如何解决呢或者您是否有相应的下载链接，不胜感激。

**Comment by vision4robotics** [comment]
感谢您的关注，json 文件可在 https://drive.google.com/drive/folders/10cfXjwQQBQeu48XMf2xc_W1LucpistPI 或者 https://pan.baidu.com/s/1js0Qhykqqur7_lNRtle1tA#list/path=%2F下载
