### ISSUE TITLE
model size mismatch

### ISSUE THREAD

**Issue by RaymondCover** [vision4robotics/TCTrack#6]
您好，我发现提供的模型文件在测试是存在无法载入的问题，想请教下您这是因为模型文件和代码不匹配的问题造成的吗？
![1](https://user-images.githubusercontent.com/48719188/164687002-d03bb305-c88c-4ec9-874d-5308cbe438c1.png)

**Comment by ziangcao0312** [comment]
感谢你的关注，我们已经测试过我们的模型是和代码匹配的，并且已经有其他人测试过我们的代码。请重新下载我们提供的模型
